// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// get cluster info such as cluster id
	// (GET /api/v1/cluster/info)
	DMAPIGetClusterInfo(c *gin.Context)
	// update cluster info.
	// (PUT /api/v1/cluster/info)
	DMAPIUpdateClusterInfo(c *gin.Context)
	// get cluster master node list
	// (GET /api/v1/cluster/masters)
	DMAPIGetClusterMasterList(c *gin.Context)
	// offline master node
	// (DELETE /api/v1/cluster/masters/{master-name})
	DMAPIOfflineMasterNode(c *gin.Context, masterName string)
	// get cluster worker node list
	// (GET /api/v1/cluster/workers)
	DMAPIGetClusterWorkerList(c *gin.Context)
	// offline worker node
	// (DELETE /api/v1/cluster/workers/{worker-name})
	DMAPIOfflineWorkerNode(c *gin.Context, workerName string)
	// get doc json
	// (GET /api/v1/dm.json)
	GetDocJSON(c *gin.Context)
	// get doc html
	// (GET /api/v1/docs)
	GetDocHTML(c *gin.Context)
	// get data source list
	// (GET /api/v1/sources)
	DMAPIGetSourceList(c *gin.Context, params DMAPIGetSourceListParams)
	// create and enable a new data source
	// (POST /api/v1/sources)
	DMAPICreateSource(c *gin.Context)
	// delete a data source
	// (DELETE /api/v1/sources/{source-name})
	DMAPIDeleteSource(c *gin.Context, sourceName string, params DMAPIDeleteSourceParams)
	// get source
	// (GET /api/v1/sources/{source-name})
	DMAPIGetSource(c *gin.Context, sourceName string, params DMAPIGetSourceParams)
	// update a data source
	// (PUT /api/v1/sources/{source-name})
	DMAPIUpdateSource(c *gin.Context, sourceName string)
	// disable a data source
	// (POST /api/v1/sources/{source-name}/disable)
	DMAPIDisableSource(c *gin.Context, sourceName string)
	// enable a data source
	// (POST /api/v1/sources/{source-name}/enable)
	DMAPIEnableSource(c *gin.Context, sourceName string)
	// disable relay log function for the data source
	// (POST /api/v1/sources/{source-name}/relay/disable)
	DMAPIDisableRelay(c *gin.Context, sourceName string)
	// enable relay log function for the data source
	// (POST /api/v1/sources/{source-name}/relay/enable)
	DMAPIEnableRelay(c *gin.Context, sourceName string)
	// purge relay log
	// (POST /api/v1/sources/{source-name}/relay/purge)
	DMAPIPurgeRelay(c *gin.Context, sourceName string)
	// get source schema list
	// (GET /api/v1/sources/{source-name}/schemas)
	DMAPIGetSourceSchemaList(c *gin.Context, sourceName string)
	// get source table list
	// (GET /api/v1/sources/{source-name}/schemas/{schema-name})
	DMAPIGetSourceTableList(c *gin.Context, sourceName string, schemaName string)
	// get the current status of the data source
	// (GET /api/v1/sources/{source-name}/status)
	DMAPIGetSourceStatus(c *gin.Context, sourceName string)
	// transfer source to a free worker
	// (POST /api/v1/sources/{source-name}/transfer)
	DMAPITransferSource(c *gin.Context, sourceName string)
	// get task list
	// (GET /api/v1/tasks)
	DMAPIGetTaskList(c *gin.Context, params DMAPIGetTaskListParams)
	// create a task
	// (POST /api/v1/tasks)
	DMAPICreateTask(c *gin.Context)
	// Turn task into the format of a configuration file or vice versa.
	// (POST /api/v1/tasks/rewriters)
	DMAPIConvertTask(c *gin.Context)
	// get task template list
	// (GET /api/v1/tasks/templates)
	DMAPIGetTaskTemplateList(c *gin.Context)
	// create task template
	// (POST /api/v1/tasks/templates)
	DMAPICreateTaskTemplate(c *gin.Context)
	// import task template
	// (POST /api/v1/tasks/templates/import)
	DMAPIImportTaskTemplate(c *gin.Context)
	// delete task template template
	// (DELETE /api/v1/tasks/templates/{task-name})
	DMAPIDeleteTaskTemplate(c *gin.Context, taskName string)
	// get task template template
	// (GET /api/v1/tasks/templates/{task-name})
	DMAPIGetTaskTemplate(c *gin.Context, taskName string)
	// update task template template
	// (PUT /api/v1/tasks/templates/{task-name})
	DMAPUpdateTaskTemplate(c *gin.Context, taskName string)
	// delete a task
	// (DELETE /api/v1/tasks/{task-name})
	DMAPIDeleteTask(c *gin.Context, taskName string, params DMAPIDeleteTaskParams)
	// get a task
	// (GET /api/v1/tasks/{task-name})
	DMAPIGetTask(c *gin.Context, taskName string, params DMAPIGetTaskParams)
	// update a task
	// (PUT /api/v1/tasks/{task-name})
	DMAPIUpdateTask(c *gin.Context, taskName string)
	// get task source table and target table route relation
	// (GET /api/v1/tasks/{task-name}/sources/{source-name}/migrate_targets)
	DMAPIGetTaskMigrateTargets(c *gin.Context, taskName string, sourceName string, params DMAPIGetTaskMigrateTargetsParams)
	// get task source schema list
	// (GET /api/v1/tasks/{task-name}/sources/{source-name}/schemas)
	DMAPIGetSchemaListByTaskAndSource(c *gin.Context, taskName string, sourceName string)
	// get task source table list
	// (GET /api/v1/tasks/{task-name}/sources/{source-name}/schemas/{schema-name})
	DMAPIGetTableListByTaskAndSource(c *gin.Context, taskName string, sourceName string, schemaName string)
	// delete task source table structure
	// (DELETE /api/v1/tasks/{task-name}/sources/{source-name}/schemas/{schema-name}/{table-name})
	DMAPIDeleteTableStructure(c *gin.Context, taskName string, sourceName string, schemaName string, tableName string)
	// get task source table structure
	// (GET /api/v1/tasks/{task-name}/sources/{source-name}/schemas/{schema-name}/{table-name})
	DMAPIGetTableStructure(c *gin.Context, taskName string, sourceName string, schemaName string, tableName string)
	// operate task source table structure
	// (PUT /api/v1/tasks/{task-name}/sources/{source-name}/schemas/{schema-name}/{table-name})
	DMAPIOperateTableStructure(c *gin.Context, taskName string, sourceName string, schemaName string, tableName string)
	// start a task
	// (POST /api/v1/tasks/{task-name}/start)
	DMAPIStartTask(c *gin.Context, taskName string)
	// get task status
	// (GET /api/v1/tasks/{task-name}/status)
	DMAPIGetTaskStatus(c *gin.Context, taskName string, params DMAPIGetTaskStatusParams)
	// stop a task
	// (POST /api/v1/tasks/{task-name}/stop)
	DMAPIStopTask(c *gin.Context, taskName string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
}

type MiddlewareFunc func(c *gin.Context)

// DMAPIGetClusterInfo operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetClusterInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetClusterInfo(c)
}

// DMAPIUpdateClusterInfo operation middleware
func (siw *ServerInterfaceWrapper) DMAPIUpdateClusterInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIUpdateClusterInfo(c)
}

// DMAPIGetClusterMasterList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetClusterMasterList(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetClusterMasterList(c)
}

// DMAPIOfflineMasterNode operation middleware
func (siw *ServerInterfaceWrapper) DMAPIOfflineMasterNode(c *gin.Context) {

	var err error

	// ------------- Path parameter "master-name" -------------
	var masterName string

	err = runtime.BindStyledParameter("simple", false, "master-name", c.Param("master-name"), &masterName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter master-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIOfflineMasterNode(c, masterName)
}

// DMAPIGetClusterWorkerList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetClusterWorkerList(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetClusterWorkerList(c)
}

// DMAPIOfflineWorkerNode operation middleware
func (siw *ServerInterfaceWrapper) DMAPIOfflineWorkerNode(c *gin.Context) {

	var err error

	// ------------- Path parameter "worker-name" -------------
	var workerName string

	err = runtime.BindStyledParameter("simple", false, "worker-name", c.Param("worker-name"), &workerName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter worker-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIOfflineWorkerNode(c, workerName)
}

// GetDocJSON operation middleware
func (siw *ServerInterfaceWrapper) GetDocJSON(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetDocJSON(c)
}

// GetDocHTML operation middleware
func (siw *ServerInterfaceWrapper) GetDocHTML(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.GetDocHTML(c)
}

// DMAPIGetSourceList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetSourceList(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIGetSourceListParams

	// ------------- Optional query parameter "with_status" -------------
	if paramValue := c.Query("with_status"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "with_status", c.Request.URL.Query(), &params.WithStatus)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter with_status: %s", err)})
		return
	}

	// ------------- Optional query parameter "enable_relay" -------------
	if paramValue := c.Query("enable_relay"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "enable_relay", c.Request.URL.Query(), &params.EnableRelay)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter enable_relay: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetSourceList(c, params)
}

// DMAPICreateSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPICreateSource(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPICreateSource(c)
}

// DMAPIDeleteSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIDeleteSource(c *gin.Context) {

	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIDeleteSourceParams

	// ------------- Optional query parameter "force" -------------
	if paramValue := c.Query("force"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "force", c.Request.URL.Query(), &params.Force)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter force: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIDeleteSource(c, sourceName, params)
}

// DMAPIGetSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetSource(c *gin.Context) {

	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIGetSourceParams

	// ------------- Optional query parameter "with_status" -------------
	if paramValue := c.Query("with_status"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "with_status", c.Request.URL.Query(), &params.WithStatus)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter with_status: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetSource(c, sourceName, params)
}

// DMAPIUpdateSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIUpdateSource(c *gin.Context) {

	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIUpdateSource(c, sourceName)
}

// DMAPIDisableSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIDisableSource(c *gin.Context) {

	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIDisableSource(c, sourceName)
}

// DMAPIEnableSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIEnableSource(c *gin.Context) {

	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIEnableSource(c, sourceName)
}

// DMAPIDisableRelay operation middleware
func (siw *ServerInterfaceWrapper) DMAPIDisableRelay(c *gin.Context) {

	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIDisableRelay(c, sourceName)
}

// DMAPIEnableRelay operation middleware
func (siw *ServerInterfaceWrapper) DMAPIEnableRelay(c *gin.Context) {

	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIEnableRelay(c, sourceName)
}

// DMAPIPurgeRelay operation middleware
func (siw *ServerInterfaceWrapper) DMAPIPurgeRelay(c *gin.Context) {

	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIPurgeRelay(c, sourceName)
}

// DMAPIGetSourceSchemaList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetSourceSchemaList(c *gin.Context) {

	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetSourceSchemaList(c, sourceName)
}

// DMAPIGetSourceTableList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetSourceTableList(c *gin.Context) {

	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// ------------- Path parameter "schema-name" -------------
	var schemaName string

	err = runtime.BindStyledParameter("simple", false, "schema-name", c.Param("schema-name"), &schemaName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter schema-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetSourceTableList(c, sourceName, schemaName)
}

// DMAPIGetSourceStatus operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetSourceStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetSourceStatus(c, sourceName)
}

// DMAPITransferSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPITransferSource(c *gin.Context) {

	var err error

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPITransferSource(c, sourceName)
}

// DMAPIGetTaskList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTaskList(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIGetTaskListParams

	// ------------- Optional query parameter "with_status" -------------
	if paramValue := c.Query("with_status"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "with_status", c.Request.URL.Query(), &params.WithStatus)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter with_status: %s", err)})
		return
	}

	// ------------- Optional query parameter "stage" -------------
	if paramValue := c.Query("stage"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "stage", c.Request.URL.Query(), &params.Stage)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter stage: %s", err)})
		return
	}

	// ------------- Optional query parameter "source_name_list" -------------
	if paramValue := c.Query("source_name_list"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "source_name_list", c.Request.URL.Query(), &params.SourceNameList)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source_name_list: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTaskList(c, params)
}

// DMAPICreateTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPICreateTask(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPICreateTask(c)
}

// DMAPIConvertTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPIConvertTask(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIConvertTask(c)
}

// DMAPIGetTaskTemplateList operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTaskTemplateList(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTaskTemplateList(c)
}

// DMAPICreateTaskTemplate operation middleware
func (siw *ServerInterfaceWrapper) DMAPICreateTaskTemplate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPICreateTaskTemplate(c)
}

// DMAPIImportTaskTemplate operation middleware
func (siw *ServerInterfaceWrapper) DMAPIImportTaskTemplate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIImportTaskTemplate(c)
}

// DMAPIDeleteTaskTemplate operation middleware
func (siw *ServerInterfaceWrapper) DMAPIDeleteTaskTemplate(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIDeleteTaskTemplate(c, taskName)
}

// DMAPIGetTaskTemplate operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTaskTemplate(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTaskTemplate(c, taskName)
}

// DMAPUpdateTaskTemplate operation middleware
func (siw *ServerInterfaceWrapper) DMAPUpdateTaskTemplate(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPUpdateTaskTemplate(c, taskName)
}

// DMAPIDeleteTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPIDeleteTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIDeleteTaskParams

	// ------------- Optional query parameter "force" -------------
	if paramValue := c.Query("force"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "force", c.Request.URL.Query(), &params.Force)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter force: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIDeleteTask(c, taskName, params)
}

// DMAPIGetTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIGetTaskParams

	// ------------- Optional query parameter "with_status" -------------
	if paramValue := c.Query("with_status"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "with_status", c.Request.URL.Query(), &params.WithStatus)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter with_status: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTask(c, taskName, params)
}

// DMAPIUpdateTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPIUpdateTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIUpdateTask(c, taskName)
}

// DMAPIGetTaskMigrateTargets operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTaskMigrateTargets(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIGetTaskMigrateTargetsParams

	// ------------- Optional query parameter "schema_pattern" -------------
	if paramValue := c.Query("schema_pattern"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "schema_pattern", c.Request.URL.Query(), &params.SchemaPattern)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter schema_pattern: %s", err)})
		return
	}

	// ------------- Optional query parameter "table_pattern" -------------
	if paramValue := c.Query("table_pattern"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "table_pattern", c.Request.URL.Query(), &params.TablePattern)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter table_pattern: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTaskMigrateTargets(c, taskName, sourceName, params)
}

// DMAPIGetSchemaListByTaskAndSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetSchemaListByTaskAndSource(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetSchemaListByTaskAndSource(c, taskName, sourceName)
}

// DMAPIGetTableListByTaskAndSource operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTableListByTaskAndSource(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// ------------- Path parameter "schema-name" -------------
	var schemaName string

	err = runtime.BindStyledParameter("simple", false, "schema-name", c.Param("schema-name"), &schemaName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter schema-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTableListByTaskAndSource(c, taskName, sourceName, schemaName)
}

// DMAPIDeleteTableStructure operation middleware
func (siw *ServerInterfaceWrapper) DMAPIDeleteTableStructure(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// ------------- Path parameter "schema-name" -------------
	var schemaName string

	err = runtime.BindStyledParameter("simple", false, "schema-name", c.Param("schema-name"), &schemaName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter schema-name: %s", err)})
		return
	}

	// ------------- Path parameter "table-name" -------------
	var tableName string

	err = runtime.BindStyledParameter("simple", false, "table-name", c.Param("table-name"), &tableName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter table-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIDeleteTableStructure(c, taskName, sourceName, schemaName, tableName)
}

// DMAPIGetTableStructure operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTableStructure(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// ------------- Path parameter "schema-name" -------------
	var schemaName string

	err = runtime.BindStyledParameter("simple", false, "schema-name", c.Param("schema-name"), &schemaName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter schema-name: %s", err)})
		return
	}

	// ------------- Path parameter "table-name" -------------
	var tableName string

	err = runtime.BindStyledParameter("simple", false, "table-name", c.Param("table-name"), &tableName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter table-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTableStructure(c, taskName, sourceName, schemaName, tableName)
}

// DMAPIOperateTableStructure operation middleware
func (siw *ServerInterfaceWrapper) DMAPIOperateTableStructure(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// ------------- Path parameter "source-name" -------------
	var sourceName string

	err = runtime.BindStyledParameter("simple", false, "source-name", c.Param("source-name"), &sourceName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source-name: %s", err)})
		return
	}

	// ------------- Path parameter "schema-name" -------------
	var schemaName string

	err = runtime.BindStyledParameter("simple", false, "schema-name", c.Param("schema-name"), &schemaName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter schema-name: %s", err)})
		return
	}

	// ------------- Path parameter "table-name" -------------
	var tableName string

	err = runtime.BindStyledParameter("simple", false, "table-name", c.Param("table-name"), &tableName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter table-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIOperateTableStructure(c, taskName, sourceName, schemaName, tableName)
}

// DMAPIStartTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPIStartTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIStartTask(c, taskName)
}

// DMAPIGetTaskStatus operation middleware
func (siw *ServerInterfaceWrapper) DMAPIGetTaskStatus(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DMAPIGetTaskStatusParams

	// ------------- Optional query parameter "source_name_list" -------------
	if paramValue := c.Query("source_name_list"); paramValue != "" {

	}

	err = runtime.BindQueryParameter("form", true, false, "source_name_list", c.Request.URL.Query(), &params.SourceNameList)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter source_name_list: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIGetTaskStatus(c, taskName, params)
}

// DMAPIStopTask operation middleware
func (siw *ServerInterfaceWrapper) DMAPIStopTask(c *gin.Context) {

	var err error

	// ------------- Path parameter "task-name" -------------
	var taskName string

	err = runtime.BindStyledParameter("simple", false, "task-name", c.Param("task-name"), &taskName)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"msg": fmt.Sprintf("Invalid format for parameter task-name: %s", err)})
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.DMAPIStopTask(c, taskName)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *gin.Engine, si ServerInterface) *gin.Engine {
	return RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *gin.Engine, si ServerInterface, options GinServerOptions) *gin.Engine {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
	}

	router.GET(options.BaseURL+"/api/v1/cluster/info", wrapper.DMAPIGetClusterInfo)

	router.PUT(options.BaseURL+"/api/v1/cluster/info", wrapper.DMAPIUpdateClusterInfo)

	router.GET(options.BaseURL+"/api/v1/cluster/masters", wrapper.DMAPIGetClusterMasterList)

	router.DELETE(options.BaseURL+"/api/v1/cluster/masters/:master-name", wrapper.DMAPIOfflineMasterNode)

	router.GET(options.BaseURL+"/api/v1/cluster/workers", wrapper.DMAPIGetClusterWorkerList)

	router.DELETE(options.BaseURL+"/api/v1/cluster/workers/:worker-name", wrapper.DMAPIOfflineWorkerNode)

	router.GET(options.BaseURL+"/api/v1/dm.json", wrapper.GetDocJSON)

	router.GET(options.BaseURL+"/api/v1/docs", wrapper.GetDocHTML)

	router.GET(options.BaseURL+"/api/v1/sources", wrapper.DMAPIGetSourceList)

	router.POST(options.BaseURL+"/api/v1/sources", wrapper.DMAPICreateSource)

	router.DELETE(options.BaseURL+"/api/v1/sources/:source-name", wrapper.DMAPIDeleteSource)

	router.GET(options.BaseURL+"/api/v1/sources/:source-name", wrapper.DMAPIGetSource)

	router.PUT(options.BaseURL+"/api/v1/sources/:source-name", wrapper.DMAPIUpdateSource)

	router.POST(options.BaseURL+"/api/v1/sources/:source-name/disable", wrapper.DMAPIDisableSource)

	router.POST(options.BaseURL+"/api/v1/sources/:source-name/enable", wrapper.DMAPIEnableSource)

	router.POST(options.BaseURL+"/api/v1/sources/:source-name/relay/disable", wrapper.DMAPIDisableRelay)

	router.POST(options.BaseURL+"/api/v1/sources/:source-name/relay/enable", wrapper.DMAPIEnableRelay)

	router.POST(options.BaseURL+"/api/v1/sources/:source-name/relay/purge", wrapper.DMAPIPurgeRelay)

	router.GET(options.BaseURL+"/api/v1/sources/:source-name/schemas", wrapper.DMAPIGetSourceSchemaList)

	router.GET(options.BaseURL+"/api/v1/sources/:source-name/schemas/:schema-name", wrapper.DMAPIGetSourceTableList)

	router.GET(options.BaseURL+"/api/v1/sources/:source-name/status", wrapper.DMAPIGetSourceStatus)

	router.POST(options.BaseURL+"/api/v1/sources/:source-name/transfer", wrapper.DMAPITransferSource)

	router.GET(options.BaseURL+"/api/v1/tasks", wrapper.DMAPIGetTaskList)

	router.POST(options.BaseURL+"/api/v1/tasks", wrapper.DMAPICreateTask)

	router.POST(options.BaseURL+"/api/v1/tasks/rewriters", wrapper.DMAPIConvertTask)

	router.GET(options.BaseURL+"/api/v1/tasks/templates", wrapper.DMAPIGetTaskTemplateList)

	router.POST(options.BaseURL+"/api/v1/tasks/templates", wrapper.DMAPICreateTaskTemplate)

	router.POST(options.BaseURL+"/api/v1/tasks/templates/import", wrapper.DMAPIImportTaskTemplate)

	router.DELETE(options.BaseURL+"/api/v1/tasks/templates/:task-name", wrapper.DMAPIDeleteTaskTemplate)

	router.GET(options.BaseURL+"/api/v1/tasks/templates/:task-name", wrapper.DMAPIGetTaskTemplate)

	router.PUT(options.BaseURL+"/api/v1/tasks/templates/:task-name", wrapper.DMAPUpdateTaskTemplate)

	router.DELETE(options.BaseURL+"/api/v1/tasks/:task-name", wrapper.DMAPIDeleteTask)

	router.GET(options.BaseURL+"/api/v1/tasks/:task-name", wrapper.DMAPIGetTask)

	router.PUT(options.BaseURL+"/api/v1/tasks/:task-name", wrapper.DMAPIUpdateTask)

	router.GET(options.BaseURL+"/api/v1/tasks/:task-name/sources/:source-name/migrate_targets", wrapper.DMAPIGetTaskMigrateTargets)

	router.GET(options.BaseURL+"/api/v1/tasks/:task-name/sources/:source-name/schemas", wrapper.DMAPIGetSchemaListByTaskAndSource)

	router.GET(options.BaseURL+"/api/v1/tasks/:task-name/sources/:source-name/schemas/:schema-name", wrapper.DMAPIGetTableListByTaskAndSource)

	router.DELETE(options.BaseURL+"/api/v1/tasks/:task-name/sources/:source-name/schemas/:schema-name/:table-name", wrapper.DMAPIDeleteTableStructure)

	router.GET(options.BaseURL+"/api/v1/tasks/:task-name/sources/:source-name/schemas/:schema-name/:table-name", wrapper.DMAPIGetTableStructure)

	router.PUT(options.BaseURL+"/api/v1/tasks/:task-name/sources/:source-name/schemas/:schema-name/:table-name", wrapper.DMAPIOperateTableStructure)

	router.POST(options.BaseURL+"/api/v1/tasks/:task-name/start", wrapper.DMAPIStartTask)

	router.GET(options.BaseURL+"/api/v1/tasks/:task-name/status", wrapper.DMAPIGetTaskStatus)

	router.POST(options.BaseURL+"/api/v1/tasks/:task-name/stop", wrapper.DMAPIStopTask)

	return router
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9W3PbONbgX8Fq92G6S7Ik23ESb81DErsz2c2tYnfNNzXVHxsiIQljEmAA0G5Nyv/9",
	"K9xIkARIyrbc1iTzMO2IuBwcnDsODr6NYprllCAi+Oj024jHa5RB9eerFDHxARK4QuyS5jSlq438PWc0",
	"R0xgpFqtKRfyv+gPmOUpGp2O5ofPD2YHs4P5aDwSm1z+xAXDZDW6HY9yyurNX85eHpXtMBFohdjo9nY8",
	"YuhrgRlKRqf/1JOYzr+VreniXygWctQ3acEFYh+g/P82jDBJ1K8J4jHDucCUjE7Vr4hzQJdArBGIC8YQ",
	"ESBTgwBCEzQa+5Z1+uLwxLs2mOJr1J6HkhQTBLiAojCzYW6mcWcQrEDlqAtKUwSJHDZFMEEe+DF3R1Jr",
	"ME0HDEpghurbpofxLKyxF6qnXWwJ3VgjuWNzwiQEJaFFmaa0SDjt/g9Dy9Hp6H9PKyKdGgqdesnzdjxa",
	"MbiEBA4e561u7w6hUVGOEKVY0zgWKON942kidIczGIGMQfXvnNEMiTUq+GAgP5dd3IFvKLu6M5x/V53D",
	"cN6Gt1J3/dP4bEELkkScFixGkSXk+pz6I5AfgWoOBNXconHWnjbb8K/pZNY1oYArz1R6ePWxZO7QJKqt",
	"b4Y2O+ohhrOjRH0dUh+ivPxJyTVikmYhv/qCvhZIU1F9bwXkV30kJQdQhAT5VRRTssSraIlTD9L0RyA/",
	"AkzABmYpWFKWQQHWQuT8dDpNaMwPckxWMcwPYppN/72eCpwsplzARYqmcpKJHqdgUI47kcNNlkWaHnjR",
	"1rdynlPC0X/k0l2KUcvxQOqlDYagQBeKgoKkoQmsD0N6EEdshWh+0k/0ZsYwxA9Eyj7M+SY9w1xuzBeU",
	"wo0zbUMOxvIPKYi4oDmAgMnmgJn24waUDpZKwd4vzz/CDL2Xrb0Ef1Zk+YWyQzwis7RPkiLLQUFwG6ZF",
	"rv6jyVXbayfHo7b5NlZWZYoESiJFsvVuCS0WKar6kSJb6G6IC5xBgSJBBUwjRm+G9lxigvkaJdFiI9DW",
	"nbaYKGd0JfWZoqSmHNdge5YcwlSTwtz+Hiy21tlcgx+FY7VzDuw+Ij4n29EwZKKXiNXXaIFJSlfRSuDE",
	"S3dMYLICby/fnVkjoci5YAhmQHetKVH0Es6X8eHhBMWzF5P5HL2cLA5hPJkdHh/CeD6fzWZHp/PJ8xfH",
	"L0fjESnSVK6rYQpXW1YDMWBNWBClnFQ2xQAwtUGxwORgJv93OByWBBsragmLVBLPwVR/0FPUYZNgJJih",
	"WFC2ATdrxJACTe9LSlcAcylwJIENgGAXUuecMcr+jsX6A+Lca0NJklF6DCDZtkVG6tcoluZUq6/6BmJt",
	"arUFke6a8VWoZ2aA6tM51UBjFx4fJ71FwljK78iShg2LWDeKfGxhvgEst60UI0VY4g51JZruWHOdDlDd",
	"a9OOjtz28AoTKOBgj6TuxXscJyXRHLnbKUUlp8jZuxeh6ffhF2FcpB0vQttUDwh9ZaTtHmxtiDwo4Ma2",
	"2TH40jZ8QJyXrsOOQf6AV0yZxmyFBH9A4GsDP8ZKHpZyikU15mNAfykV8IVgRSwKhsKr0ABGsXJoIv41",
	"rTtLb76cv7o8B5evXr8/B7+L+e/gL7/j5HeAifjLfP4T+PjpEnz89f178OrXy0/Ru49vvpx/OP94Of78",
	"5d2HV1/+Af7/+T90j5/A9OfL//VPI/dREmGSoD9+A2/e/3pxef7l/Az8PP0JnH98++7j+V/fEULPXoOz",
	"819e/fr+Erz526svF+eXfy3E8kW2OAZvPr1//+ry3P5bmlW+cIdZWtsDTBbeAIyyfj3N1e/zAR5v2d2O",
	"5WDVu1WNoOCDh72PZrPZvcPe7ylM+t25lMLkvu5ch3cV7pQhAY1h7XWWnO+lb9DGXL+7NRymBn5bvpQ7",
	"njN1fSkewLV/5duiRjT4vnQUCtsPorkXhyfzXpwYLukjvU/KYkfdgbN4jeKriCGu3JgmheYMTVQLYFq4",
	"3lP1EXOQQ85RcgD8ouE+wZxxHcaelTYld6+TrP0aBJTMCTrJy7Tg65rHp52z+qh/Z1ggrnw7vS4d0kZA",
	"rSCnmAjA5S9QgLMPIIZEcz4WAC6lJ8FQ6cfKbjYM2Doa4l/TKKZEIOJZG/+agg0twA0kwllhbe88mgn8",
	"Hs8r1WS1h1RPY/B7fBj+dOT/dA999H+9CmlD4vZif80TaHFOc4EzzAWOAV9Dlkg0SjkgtT24wWKtI/9m",
	"ayhJN6DgKJEeOQHQOLaAxnHBOMAkOObZ2XuQ1ZzZcmuaQVBnn3yE6zkz2sXp7f3V2OeC+YICVQQjlusv",
	"cpDTFMcbUIt8t2MFf+SYGTvQ8tOsyUyqkY44CKzjOeV0rr9tFUkgbuIoO/knu9aGYjnv0cmsNfXlGgHb",
	"WHJQjhimCY5hmm6AEXnLdghHLysZAzM4uIZpgU6BmkISFEcxJQm/G/QMZRCTiOcwRrUVzJ814f+ACc6K",
	"DCwZQiDB/AqoXgqGt6/vMv1tiCYeNJ7+iHG+vrhebc4cxXi5McDzYuFE85aUgRbYB+DdEhAqgO6JJU2o",
	"s38pqgSgBIEbnKZggZQAOgAXClJzxnQKDiF6fnJ8dDxZPn+5nMzn6MVkkaBDGz6VhukLvZR5f8Cwwelt",
	"HPv4XW3rG8XEbXwojaaPyCxTtllcRaoj/bGyCx0d9iPuvFdx59sQlfR7N67YrlOJyeKoHJD6EA0c2gNZ",
	"zSZasVRI/UsDq/MxmL98/vInH7PX5g0Qn4/m7kFs3cTlB0EjzmZjSIAeHoAYingdFXmUlZlZdSBu1tJC",
	"YVKIq7agyLUxVe6O44SF2NwrV7ejz2rdB1NeLNSQPjPRnwJikaipsjbcl4IQ2blPctaJ1UtE7nJ9OxxC",
	"ugXbJ4ovlLlaHt+0+Uybs0r2qOOgcRVU64/aNAJpFyguGBab9jTKiDY5O5yndQtPq7clRmlSarY1ThJE",
	"tHG9QqJ0atyBaoOAJaOZaqJsr6W0c9piqeG+IiYimKb0BiVRTNpgv6FZRgn4aCTzxcV7IPvgJY6hDiGU",
	"yOpFDudpFMOw4+UMrEWVbelSm5dm5cByJcGhf3GGk+v4fP7BWAvT/3o2e2mzUxpL65/1Cm3Ck76p5pO7",
	"kjN8LZd2hTZlaowzec98Tc+ojksPDtoAernDOGVvGS1yT5g5Sdspd70bvcSMiyilsdYyvi7SG0XJdsMK",
	"HX33NS3I9gO2giVq9HG15tZCSrCdCb1ILbOFfCl7AVuvZpcsYcpb4ZFSkygvXEsA6Tap7jURb7q3tYkx",
	"Kyt1OWg+Ks1sbURKb66QAkpJZa5ljk+9B0FYpvCaerSZ/r3MLyxx1TD7fJxoXXxvgqTJzfQnYHojAJDz",
	"G8qS4Ihlg/qQR8fPToZYojbC4B9bfnTGPTqanfi82dwGFDpTalWjylQp/ZGuTq7rIhnV0WidZ0y2newz",
	"MG91cHaqtjq2S/7tPS6F/Gp4Esgl5FdVCsh4VHCfrWfWJj+21scoFQOz/iJPhNpMWWdh+68OKdRh+DgJ",
	"xGHDR7eaDLN+XJSH5istSF/+S38SizaIuIr7SZPohlGf7WlpnpfA9NJ8RSr3oF+G8hTHMEDHjbTQdtTM",
	"ZFUbazvduJndyCcTt8wntZTlAuKlHemWd2aYMpTRaxRlSJ9DD9Ykup+KKytTdgG5soQSekOMP2R/9ofu",
	"4RJFGU1QJHCGosTGSNveEc4QsJ+lWpE9bdzZkdsz7pU4FboGyYcGs2mZxYQC0gMb5FcmvVA1cAE6nM1O",
	"JrP5ZHYI5s9OZ8ens2fDUr0vBM07t+z+a5LA0kIMxvoNxNpv0euleR31z/jAldXyF9pGapHlAxndyQ7e",
	"InFusMxJKUwGQuIcbDuHnh4ysWf6HRTaJ6TCTn6fyrtQDY29PnBlFxsSVytTp/L+lclPQMHmUoU6pxr7",
	"THyGOE2vURIpC53GV1HgQL1TzNqLK17U+E+Kw7LTotKs0ytKK3R0xPjkqgMZDDr+ocf1LHYhMYHJSmLF",
	"N4V76nazxvG6DIhhDmznrfx4xW+YRqHUhI4Mzrv1aoU5BwYkPTZBjIiIxOCkEHPiFC3QGpPEifEN6Vt6",
	"pB4tJr91rqjWIrwijU10bS+3DoDLJOAPxoHDeCtGi7yLyHSDBp1BhkBBJnYUl9Y65UgtNNHrvruIcBdZ",
	"2/XxsChkfXu8m9FkPB+enHiBy8Uhsmqxh5/VfEJGpW3cN8YZSjVrS4BLk5HSFuoh8bXEqUQzK3SgAyYJ",
	"lr1g+rnWuk8fvcbkPV39ogb7IsfymQuIrCGJUaRvJUc2yXANyQr15qA4pqr2rQAvcumBqaNKldKgLzsn",
	"SQrytFhhMuQyMl4RylCkDr8lzZTob1x4Vs1AzpA5JlfNvLt1jRjXQane7cogwzBZTCRS4SBX94Pscfb6",
	"jepQBQNUVphuVz9GS7KJ8gSa2PRY9QqPXFBm00uCJ1LVoMEksbC95JI1v/L7r5RESaH8NeEZbU1vJBWs",
	"IUl08HiZ4ligRK1Eud5Fpk+E81TH2u3NDr2LDqM6Yl0KNeW/+M9zbuBGnRRRKmUfFEjqbWeyHHFuEmpG",
	"41GVXeOfTNstw+I+ytxTHZzgz13iLn3JxhK+WEQV7FETKQNdScufarxWplHL1Quxps6WzXSGdymhmpQl",
	"ZzJtgGozHp49rqSzSSFvSK1GcHuLvdK56GdQwNfSV7YRLT9pWcgtTgw1LYs0lQshMUMZIjq5G6rfpOYZ",
	"aY9G0lbFTvrzILu5AqhHKDdYsYkN7x41yduvFj0qw3c4JJASR3JgDqCwB+YpukZpS6UZWa5sDY/nKH+2",
	"bk1AzNfa1FALkiwdItINDCZlvp3AmEMhEFOpQ1r1hoEJNa/g+u8zplz3/gMV7w78UqSpoX4pWkL3xZ1Q",
	"jaTLktskFbXjhZDAdPNvH6tSddDHaKpTzXiRySHz9YbjGKYAZzbGXspvQ7hankqjRP65XNbp3vnWwoOd",
	"6IlAQ7OcIc4nV9eTHGLGu8EyrcHVNVCt/fB5ZiEcc4FIvOkc32o1TIxboA6wdbofZVKfLtXlxnI0ADkv",
	"mBQWdeYoBPXBIYcL5J0JyuBK5Ui0rYKDqZ0/Mvq8PTLmV9HXgtoIZ82wwfwKqG8KfM9+ljO9mL31ja6n",
	"j8SaIZjUczmPm0pP8YPuIHcnpsT4Vn4nW8EQMjKqndHtlE4oma5FjyldyYVJ/jNrrBNi9b21QgOHb4Xz",
	"E+8SDUT9S3TVRWRB6KNC20MKGeWqFTpIuUYEZAiJsgECjN5wtbFmbB+fhq0+59CnbNVpfEYlbnexhrCw",
	"IZQg5QOTormv5lP79DKJemvg5N4CMEyq+qjcWCs2QvnLzsJVT+D07BRR9fDNHQ4vVUJiQKToj6VI6WX+",
	"g6ns4k+2CunLdyRm2+lLx4ALqEtJiNECirh+C2PeTt52x+IbEq8ZJfjf5VRqDID+QLGmPGk9fC0gEVhN",
	"5c+8ztOBUqC5kF5REMKhz4Ft4dE0sjcaYlUrRzrVPfn3ia6FkkyUvejJO1RmJPpDciIW6QbYDopc7Kza",
	"G8cLnGKxcSb3u/tFgZOJxdwAA9FkhQwG0bS/B4QxTVOLr/6QhFc5GYbnwHp5fZA08l+MWDOmgoKkZTmF",
	"7AjtRk629kKXEKfmCkwAXIlrEENCqAALBGCep3hQvk6QuGu3kf1hkMp6VnehWzRsnKcqmNOb62h6CJus",
	"5ERYQldalRO3xRSmx9Ap/EfcZr4GwE1wGpOFvMdwTLUMNnVGVPnV4IBqFXxpH3E2jgGqGWZHy3h2eHI0",
	"OXwRP5/M5+j5BJ48O5qcxLPFi+Pk2cvl0ex0Pnk+O54fHx6NZ8+Onx8nR7HT/MXRs8PJ4ewoWRwenyTJ",
	"UXI6n8yfz7xF4uqZ/E7RN/WhulIR6pnTOoKOvUp7N9kXHfkQoc2vhcMCoEwYSqH0YrpVhjRvy/hFbPa4",
	"L8TTdJxvdahm63GaBkU9NBhEcnNFg+NdDiX3Hdu4cAS3wZ5WW/l+IWieKwla5Z7/Yi46j8ajz7DgtczM",
	"ig690bjwvQkd9hPUzU5xg4B84HFHw9VRH7VaMITskR3y87C0q2HF6XxLd2qhlLpk2zFsTYzh9es6ILkf",
	"k7knE4HjrzG4wWkSQ5bYc536kcNi8vM9ky1aqXOhJAxRZf22Q80DYBVeWDvTvhzdp5ReYDNChkXFBQ+5",
	"IQlFXN/2MwdtdtW8sTXzO2Jx4AQhEyNAv7XoeweqqoOvblw9qSTm3SQt38Ud31GirTe1tsRJUGqhLJd0",
	"H0yxo9eI3TAstnMhyl7a5xVmlvKP/ovy1bz9oIdKWUhHRpVh5FftE7+OZF1vvYpSVPYXarXCqRrUt4aW",
	"0iviGHEeAHe7qx/tscZtbPiA0tUTHrR27HA1qid/5DKwjWKIXdl1HX5ROGu5vdHVjMFr8uY+PAdWKwlq",
	"Mql5V83ZvtzAO2RZ9+VVNyqSP3ytnGBN7Z0Wy7lV5xlCCuP0jMaeeNPZB/ApR+TV53fg7NMbKXJZOjod",
	"9ZWDnkjlOdEmN6bEVIfWjtCSKhLHQi28NYGNVZ2OTiQCVcg9RwTmeHQ6OlI/SYkv1graKczx9Ho+NSXC",
	"pnZ4YweV1TvfJWquV5/f1StgqjQzLVnVeIezmbpfWd0NVGEfHbmf/ovr3OnKPuos3++vtamw3lCLWpCp",
	"TeRFlkG2GZ3KNYCy1iZZUsCLeA0gB7UCnAKuuFMcUxmHeRFavRY+TQQoNnxNk82Drb1dyrO1aDMtWMh5",
	"b5/wPhQKZ7WtOPAi/nbcokedIsiHkmRVuPRxCNNTKLULLePR8QOC0Sq+65laq/MOxnDearCKa5uNmX7T",
	"fyhv71bLvxRpO9CzU5+WyxQTpNH2UWfI5JDBDOld/mcrgccBz8YMVIUxKNYjqwhGDgwjV4zr1CdfIDb8",
	"JMpvLcI59tjhT2xHqcZr4+WNQRtpDYaBHFZV1X0cDvNU8d0zDnNeDNmKw8zGTL8ZK2wrDjPW4wAOc8EL",
	"c5gDw/fNYfX3Xzo3MskOLHBeznqLxBmN/9/Fp48BVqqDJccqS0O0yS2hMVDTVVAlNG5AZGzUDnD+dvnh",
	"/SBwZMMecNZCJ/WFwNFOXr/oqWph9xGz5C9bIkAVmylv3Sqa/logtnGIGot1VLbwELE/dfZ27HkHbAMY",
	"EgXT1f/00ezEFP6yt1d9INTqXW0Dw2+7lb6e8uMeTnFrsqT2kYAGHTSbVPRgfXzlo/HQ/rvv1OzK2PY8",
	"hbO9wT1/MHjKmMiT13O61jKAJLFZ6RAQdOPuum/D2zJg+s05NejXcmfqY0kUnTJhldKFqsBYEPy1qBcS",
	"Ciu8+iHGIIUXLOTQFhhLqksC0NxCAlNuqh3aUlYqoGOSmnyiQ41xT5mxB4pX0wGAfTQ1HqJD9pFWHken",
	"7VKfdMiz8iD22EuLBvNUgKV6X6+tX7oIoi+Mszc08dtu9J4vjH9bD4RKcG//HNJ4YnLIRLHgfXXb1CRF",
	"qiB42Owx787tF4n2+QxPTrdoJD/Apla1zDr2VD/D9mNLd7mlpRl63x1VLtl2zPrFljT+PtWJ76nMW6NP",
	"9lUyVDVllwXRVcntffiHIbAtBMd3Tl6eRyz3lbqMkNo5cZXVEjtoqyrH//2SVvtJguFm8NOmNEUBtUrq",
	"29OSAWJgmFbXnR4SrN0B6YSrNu7Wwa3X2t6TAypbmFInpYaCs0PJY/pN/1FF8AYQi8rAfXq0Mu5I3A1M",
	"X6194PTevN6dUmm9WNJ+EanOa747jZaF6IZIsLJS69PRhp03fB7lLKjxMueekI96c6b2hoMtS39fC0sw",
	"SPhSJ2l3mFeXptn3Hmtsp7P+p5hYlhBKUUUB1E9o6VyBHurSRzx9ksk+TNxLQJLmIb96zNNvc69rsbH1",
	"bnVlUN+c9ttQhVVWYu2a1cMfzWmbFYDHW4WnHZ25Y1Hben/aQ4QKyampTPx0BG0JVUXuOpt+yPH+pS6h",
	"uLvDffe6wJ95tO97XHWPzvnLp0XrO9wUZ1OG1K0cnVbYtfuqooHY5fbrGRDroQC81CSMOcAkL4R+jcOI",
	"Uv0yUWyG0nXpIb8yJdj0qzaUgWscI3CNGIc7paHGkvaHii5VfpTCMjGl/c0DRHQJYPNVpxZSDwYQnr06",
	"Nkyj2sthj5DOuueSvbybdy8Rf1ld7NsFr5srXX+edA8B8ETFeW1nt2Guqan41C3c36lGj7TvzSuq25PB",
	"4Y7g2R/5bMrQ3Z0svqmaw9uk8DWoYyvn2C177PGKS1gG+sShesl7nTYXvljdFOCDleX+bNPsuxPsbX3d",
	"teXB/LjqivWPTd+bzLSh+96S33eT2k+VIrpyrRUM6BoRgJfqXSPAi4V1+1hZU+lHtnXI0R+gJvaGLh4h",
	"VPpnSKeGE3kcquDXkVMd3v2+jOqnTAA7TaK+X3xx9r3HF8vk6oHxRUdlBY7nbK1AWwd0SDioVl+U740g",
	"e/TcCO8Ri37YwjyoMArlPPw8fET99kX3gKrNz49/JN6mlr07GFdHdW5yBSSJqZprfmC0EOYqGq7dK747",
	"Vw5OJSuTyF5vJK5fkeRuB+jfCVP+SG7rom9/htu9qXjLjLcy1+0HSf/IwdtbXvIm4j0wK8l+ixRtGZJY",
	"pOhCsCIWBfvBU0+Np8bhQrUhlFsKGIxz/yue+x++r3Eed0h82+DMDw75wSHzP8dZqhPf/jtLnWwYjpKV",
	"4ZkfrLj15N8LIz58iNIJCjb58D8rFVtz3JZqs9tqFbA3z+VCtvkOI9/luvf9Oq7a5DsGn4ddLHJeht5D",
	"YV9WNN/31Po9vcNkblVo6tmOOmneK7xo/l3KLr3s/RddNA9LLvX2CLu2O1qvPb+hxUFCM4iJqjw/kqg2",
	"A/hlwaiv2H1C48EV7k1J++nXAsdXEyWBJzotdVIVBavJmJHPMlPL3i1UN1isJ0nmwKOmbUNji8CW7ewP",
	"t7/d/k8AAAD//+zggE2NwQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
